packages:
  - apps/*
  - packages/*

catalogMode: prefer

catalogs:
  dev:
    '@antfu/eslint-config': ^6.4.1
    '@modelcontextprotocol/inspector': ^0.17.5
    '@vitejs/plugin-vue': ^6.0.1
    '@vue/tsconfig': ^0.8.1
    eslint: ^9.39.1
    npm-run-all2: ^8.0.4
    pkgroll: ^2.21.4
    tsx: ^4.20.6
    turbo: ^2.6.3
    typescript: ~5.9.3
    vite: ^7.2.4
    vue-tsc: ^3.1.4
    '@tailwindcss/vite': ^4.1.18
    tailwindcss: ^4.1.18
    vite-tsconfig-paths: ^6.0.2
  prod:
    '@modelcontextprotocol/sdk': ^1.23.0
    express: ^5.1.0
    ollama: ^0.6.3
    openai: ^6.10.0
    vue: ^3.5.24
    zod: ^4.1.13
  test:
    vitest: ^4.0.14
  types:
    '@types/express': ^5.0.5
    '@types/node': ^24.10.1

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - esbuild

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - tailwind-merge
  - rxjs
