packages:
  - apps/*
  - packages/*

catalog:
  '@tailwindcss/vite': ^4.1.18
  tailwindcss: ^4.1.18

catalogMode: prefer

catalogs:
  dev:
    '@antfu/eslint-config': ^6.4.1
    '@modelcontextprotocol/inspector': ^0.17.5
    eslint: ^9.39.1
    npm-run-all2: ^8.0.4
    pkgroll: ^2.21.4
    tsx: ^4.20.6
    turbo: ^2.6.3
    typescript: ~5.9.3
    vite: ^7.2.4
  prod:
    '@modelcontextprotocol/sdk': ^1.23.0
    express: ^5.1.0
    ollama: ^0.6.3
    openai: ^6.10.0
    zod: ^4.1.13
  test:
    vitest: ^4.0.14
  types:
    '@types/express': ^5.0.5
    '@types/jsdom': ^27.0.0
    '@types/node': ^24.10.1
  ui:
    '@iconify/vue': ^5.0.0
    reka-ui: ^2.7.0
    tailwind-merge: ^3.4.0
    tailwind-variants: ^3.2.2
  vue:
    '@tsconfig/node24': ^24.0.3
    '@vitejs/plugin-vue': ^6.0.2
    '@vitejs/plugin-vue-jsx': ^5.1.2
    '@vue/test-utils': ^2.4.6
    '@vue/tsconfig': ^0.8.1
    '@vueuse/core': ^14.1.0
    jsdom: ^27.2.0
    pinia: ^3.0.4
    vite-plugin-vue-devtools: ^8.0.5
    vue: ^3.5.25
    vue-router: ^4.6.3
    vue-tsc: ^3.1.5

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - esbuild

shellEmulator: true
