packages:
  - apps/*
  - packages/*

catalog:
  '@vueuse/core': ^14.1.0
  reka-ui: 2.6.1

catalogMode: prefer

catalogs:
  dev:
    '@antfu/eslint-config': ^6.4.1
    '@modelcontextprotocol/inspector': ^0.17.5
    '@vitejs/plugin-vue': ^6.0.1
    '@vue/tsconfig': ^0.8.1
    eslint: ^9.39.1
    npm-run-all2: ^8.0.4
    pkgroll: ^2.21.4
    tsx: ^4.20.6
    turbo: ^2.6.3
    typescript: ~5.9.3
    vite: ^7.2.4
    vue-tsc: ^3.1.4
  prod:
    '@modelcontextprotocol/sdk': ^1.23.0
    express: ^5.1.0
    ollama: ^0.6.3
    openai: ^6.10.0
    vue: ^3.5.24
    zod: ^4.1.13
  test:
    vitest: ^4.0.14
  types:
    '@types/express': ^5.0.5
    '@types/node': ^24.10.1
  ui:
    '@tailwindcss/vite': ^4.1.18
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    lucide-vue-next: ^0.561.0
    reka-ui: ^2.6.1
    tailwind-merge: ^3.4.0
    tailwindcss: ^4.1.18
    tw-animate-css: ^1.4.0

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - esbuild

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - tailwind-merge
  - rxjs
