packages:
  - apps/*
  - packages/*

catalogMode: strict

catalogs:
  dev:
    "@modelcontextprotocol/inspector": ^0.17.2
    turbo: ^2.6.2
    tsx: ^4.20.6
    typescript: ~5.9.3
    "@vitejs/plugin-vue": "^6.0.1"
    "@vue/tsconfig": "^0.8.1"
    "vite": "^7.2.4"
    "vue-tsc": "^3.1.4"
  prod:
    "@modelcontextprotocol/sdk": ^1.23.0
    express: ^5.1.0
    zod: ^4.1.13
    vue: "^3.5.24"
  test:
    vitest: ^4.0.14
  types:
    "@types/express": ^5.0.5
    "@types/node": ^24.10.1

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - esbuild
